spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: database
      database: ${MONGO_DB:person_react}

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_test
    protocol: r2dbc
    password: postgres
    username: postgres

  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7001