spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: database
      database: ${MONGO_DB:person_react}

  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7001